### ISSUE TITLE
no data on grafana

### ISSUE THREAD

**Issue by dev-minds** [cloudquery/grafana-dashboards#2]
Thanks for this combo with cloudquery - 

However i have setup all tools 
- cloudquery [successfully fetched dsn]
- PostgreSql [data on the postgres default db]
- Connected postgresql as a datasource for grafana 
- Imported 2 of the dashboards, but dashboard is empty :( 

Any help with this ? 
Would highly appreciate :)

**Comment by yevgenypats** [comment]
@dev-minds Thanks! taking a look at that.

**Comment by bbernays** [comment]
@dev-minds - We are looking into this now, can you specify the versions for the following pieces:
`cq-provider-aws` -- You can find this in the `config.hcl` file in the provider section
`cq-provider-gcp` -- You can find this in the `config.hcl` file in the provider section
`cloudquery` -- you can find this by running `cloudquery version`

**Comment by dev-minds** [comment]
cq-provider-aws [I am using aws in my case]
```ruby
  provider "aws" {
    version = "latest"
  }
```



cloudquery version 
```ruby
Version: 0.17.4
Commit: 0b263828ec1e0908ad4f960ab9148ec078ffdade
Date: 2022-01-03 21:21:11.303337 +0000 GMT m=+0.008852660
```

-
Thanks for looking at this

**Comment by bbernays** [comment]
Ok all of that looks good. A few more questions:

1) Which Dashboards did you import?
1) Where is the database actually running? RDS? EC2?
1) Can you verify that there is actually data in the database? 
1) Is Grafana self hosted or the cloud version?

If you would prefer feel free to reach out to me directly via email ben [@ ] cloudquery [.] io

**Comment by dev-minds** [comment]
1. I have imported the `aws_ec2_images and aws_iam` files 
2. data base is hosted on a postgresql container 
3. Yeap, i can confirm there is data in the DB 
```ruby 
psql -h localhost -p 5432 -U postgres -d postgres
Password for user postgres: 
psql (14.1)
Type "help" for help.

postgres=# select * from aws_ec2_images \x\g\x
Expanded display is on.
-[ RECORD 1 ]--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cq_id                | 95aac537-93dd-59cxxxxxxxxxxxxx
meta                 | {"last_updated": "2022-01-03T11:24:21Z"}
account_id           | 6xxxxxxxxxxx
region               | eu-west-1
id                   | ami-0002dcfbxxxxxxxxx
architecture         | x86_64
creation_date        | 2021-05-17T08:21:30.000Z
```
4. Grafana is also hosted on a container, and when i add the datasource it connects successfully

**Comment by dev-minds** [comment]
Yeah happy to ping u via email

**Comment by bbernays** [comment]
@dev-minds - I have successfully recreated the issue on my machine. I will give you an update by EOD tomorrow about next steps

**Comment by bbernays** [comment]
Under the data source, can you set the `TLS/SSL Mode` to `disable` and retry?

**Comment by dev-minds** [comment]
Yeah i disabled TLS/SSL while loading the dashboard, but i can try it again

**Comment by bbernays** [comment]
I just found out that Grafana will show you a `Database Connection OK` message even when there is an error. 

Here is the response I get in the browser:

```
{"results":{"tempvar":{"error":"db query error: pq: password authentication failed for user \"postgres\"","frames":[{"schema":{"refId":"tempvar","meta":{"executedQueryString":"SELECT 1"},"fields":[]},"data":{"values":[]}}]}}}
``` 

Can you validate that the username + password is correct and also look at the browser traffic to make sure you are not getting a 400 error like I did?

**Comment by dev-minds** [comment]
Ahh yeah, that is what got me mostly confused. 
But i fixed it now, essentially my postgresql container was listening only on localhost, so thought i should spin it up with all interfaces 
```ruby
docker run -p 0.0.0.0:5432:5432 -e POSTGRES_PASSWORD=pass -d postgres
```
Then used an actual IP, from my host machine for the datasource host value. This fixed it, i can see data coming through now :) 

Thanks for looking at this

**Comment by bbernays** [comment]
Great! I am glad we could get it working for you.

I have opened a bug with the Grafana repo. Documenting that the UI always indicates a connection success
https://github.com/grafana/grafana/issues/43638
